//
//  DetailFilmPresenter.swift
//  filmSky
//
//  Created by André Brilho on 11/06/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailFilmPresentationLogic{
    func showName(name:String)
    func showDesc(desc:String)
    func showImage(imgUrl: String)
}

class DetailFilmPresenter: DetailFilmPresentationLogic {
    
  weak var viewController: DetailFilmDisplayLogic?
  
   func showName(name: String) {
      viewController?.showName(name: name)
  }
  
  func showDesc(desc: String) {
      viewController?.showDesc(desc: desc)
  }
    
    func showImage(imgUrl: String) {
        viewController?.showImage(imgUrl: imgUrl)
    }
}
