//
//  DetailFilmViewController.swift
//  filmSky
//
//  Created by André Brilho on 11/06/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AlamofireImage

protocol DetailFilmDisplayLogic: class {
    func showName(name: String)
    func showDesc(desc: String)
     func showImage(imgUrl: String)
}

class DetailFilmViewController: UIViewController, DetailFilmDisplayLogic {
    
    @IBOutlet weak var img: UIImageView!
    @IBOutlet weak var lblTitle: UILabel!
    @IBOutlet weak var txtDesc: UITextView!
    
    var interactor: DetailFilmBusinessLogic?
  var router: (NSObjectProtocol & DetailFilmRoutingLogic & DetailFilmDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }

  private func setup()
  {
    let viewController = self
    let interactor = DetailFilmInteractor()
    let presenter = DetailFilmPresenter()
    let router = DetailFilmRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }

    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.load()
    }
    
    func showName(name: String) {
        lblTitle.text = name
    }
    
    func showDesc(desc: String) {
        txtDesc.text = desc
    }
    
    func showImage(imgUrl: String){
        img.image = UIImage.init(named: "emptyImage")
        img.af_cancelImageRequest()
        img.af_setImage(withURL: URL(string: imgUrl)!)
    }
}
