//
//  DetailFilmInteractor.swift
//  filmSky
//
//  Created by André Brilho on 11/06/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailFilmBusinessLogic {
  func load()
}

protocol DetailFilmDataStore {
    var selectedFilm:MainFilm.Film? { get set }
}

class DetailFilmInteractor: DetailFilmBusinessLogic, DetailFilmDataStore
{
  var presenter: DetailFilmPresentationLogic?
  var worker: DetailFilmWorker?
    var selectedFilm: MainFilm.Film?
    
    init(worker:DetailFilmWorker = DetailFilmWorker()) {
        self.worker = worker
    }

    
    func load() {
        presenter?.showDesc(desc: selectedFilm?.overview ?? "")
        presenter?.showName(name: selectedFilm?.title ?? "")
        presenter?.showImage(imgUrl: selectedFilm?.cover_url ?? "")
    }
    
}
