//
//  MainFilmWorker.swift
//  skyTestFilm
//
//  Created by André Brilho on 11/06/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class MainFilmWorker {
        
    func getFilms()-> Promise<[MainFilm.Film]>{
          let url = URL(string: Constants.URL_BASE)!
                return Promise<[MainFilm.Film]> { seal in
                    URLSession.shared.dataTask(with: url) { (data, response, error) in
                        if let data = data {
                            let objParse = try! JSONDecoder().decode([MainFilm.Film].self, from: data)
                            seal.fulfill(objParse)
                        } else {
                            seal.reject(NSError(domain: "", code: 0, userInfo: nil))
                        }
                        }.resume()
                }
            }
        }
