//
//  MainFilmPresenter.swift
//  skyTestFilm
//
//  Created by André Brilho on 11/06/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainFilmPresentationLogic {
    func reloadTable()
    func routeToDetail()
    func showError()
    func showData(listFilm:[MainFilm.Film])
}

class MainFilmPresenter: MainFilmPresentationLogic {
    
    weak var viewController: MainFilmDisplayLogic?
    
    func showData(listFilm: [MainFilm.Film]) {
        viewController?.showData(listFilm)
    }
    
    func reloadTable() {
        viewController?.reloadTable()
    }
    
    func routeToDetail() {
        viewController?.routeToDetail()
    }
    
    func showError() {
        viewController?.showError(erro: "OPS")
    }

}
