//
//  MainFilmRouter.swift
//  skyTestFilm
//
//  Created by André Brilho on 11/06/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainFilmRoutingLogic {
    func routeToDetail()
}

protocol MainFilmDataPassing {
  var dataStore: MainFilmDataStore? { get }
}

class MainFilmRouter: NSObject, MainFilmRoutingLogic, MainFilmDataPassing {
  weak var viewController: MainFilmViewController?
  var dataStore: MainFilmDataStore?
    
        func routeToDetail() {
            let storyBoard = UIStoryboard(name: "Main", bundle:nil)
            let detail = storyBoard.instantiateViewController(withIdentifier: "detailVC")
            var destinationDS = (detail as! DetailFilmViewController).router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            viewController?.navigationController?.pushViewController(detail, animated: true)
        }
        
        func passDataToSomewhere(source: MainFilmDataStore, destination: inout DetailFilmDataStore) {
            destination.selectedFilm = source.selectedFilm
    }

}
