//
//  MainFilmModels.swift
//  skyTestFilm
//
//  Created by André Brilho on 11/06/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainFilm {
    
    struct Film:Decodable {
        
        var title:String?
        var overview:String?
        var duration:String?
        var release_year:String?
        var cover_url:String?
        var backdrops_url:[String]?
    }
    
}
