//
//  MainFilmInteractor.swift
//  skyTestFilm
//
//  Created by André Brilho on 11/06/20.
//  Copyright (c) 2020 André Brilho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainFilmBusinessLogic {
    func didSelectRow(indexPath: IndexPath)
    func load()
}

protocol MainFilmDataStore {
    var selectedFilm: MainFilm.Film? { get set }
}

class MainFilmInteractor: MainFilmBusinessLogic, MainFilmDataStore {

    var selectedFilm:MainFilm.Film?
    var listFilm:[MainFilm.Film] = []
    
  var presenter: MainFilmPresentationLogic?
  var worker: MainFilmWorker
    init(worker:MainFilmWorker = MainFilmWorker()){
        self.worker = worker
    }
    
    func load() {
        worker.getFilms().done(handleSuccess).catch(hanldeFailure)
    }
    
    func handleSuccess(model: [MainFilm.Film]){
        presenter?.showData(listFilm: model)
        listFilm = model
        presenter?.reloadTable()
    }
    
    func hanldeFailure(error:Error){
        presenter?.showError()
    }
    
    func didSelectRow(indexPath: IndexPath) {
        selectedFilm = listFilm[indexPath.row]
        presenter?.routeToDetail()
    }
}
